version: '3.8'

services:
  mmysql:
    image: mysql
    container_name: mysqldb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cdas
      MYSQL_USER: cdas
      MYSQL_PASSWORD: cdas

    ports:
      - "3308:3306"
    networks:
      - spring_mysql

  spring-boot-app:
    container_name: cdas
    build: ./
    restart: always
    ports:
      - "8080:8802"
    depends_on:
      - mmysql
    environment:
      MYSQL_HOST: mmysql
      MYSQL_USER: cdas
      MYSQL_PASSWORD: cdas
      MYSQL_PORT: 3306
    networks:
      - spring_mysql
networks:
  spring_mysql:
    driver: bridge